[versions]
log4j = "2.25.3"
grpc = "1.79.0"
protobuf = "4.33.5"
reactor-netty = "1.3.3"
reactor-core = "3.8.3"
armeria = "1.36.0"
classtransform = "1.14.1"
kyori = "4.26.1"
jooq = "3.20.11"
flyway = "12.0.1"

[plugins]
protobuf = "com.google.protobuf:0.9.6"
jmh = "me.champeau.jmh:0.7.3"
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }

[libraries]
gradle-plugin-shadow = "gradle.plugin.com.github.johnrengelman:shadow:8.0.0"
gradle-plugin-lombok = "io.freefair.gradle:lombok-plugin:9.2.0"
gradle-plugin-indra-git = "net.kyori:indra-git:4.0.0"
gradle-plugin-loom = "net.fabricmc:fabric-loom:1.15.4"
gradle-plugin-spotless = "com.diffplug.spotless:spotless-plugin-gradle:8.2.1"
gradle-plugin-freefair = "io.freefair.gradle:maven-plugin:9.2.0"
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
log4j-iostreams = { module = "org.apache.logging.log4j:log4j-iostreams", version.ref = "log4j" }
log4j-jul = { module = "org.apache.logging.log4j:log4j-jul", version.ref = "log4j" }
jline = "org.jline:jline-terminal-jansi:3.30.6"
jansi = "org.fusesource.jansi:jansi:2.4.2"
ansi4j-core-api = "com.github.PavelKastornyy.ansi4j:ansi4j-core-api:ansi4j-1.1.0"
ansi4j-core-impl = "com.github.PavelKastornyy.ansi4j:ansi4j-core-impl:ansi4j-1.1.0"
terminalconsoleappender = "net.minecrell:terminalconsoleappender:1.3.0"
slf4j = "org.slf4j:slf4j-api:2.0.17"
disruptor = "com.lmax:disruptor:4.0.0"
picoli = "info.picocli:picocli:4.7.7"
picoli-codegen = "info.picocli:picocli-codegen:4.7.7"
commons-validator = "commons-validator:commons-validator:1.10.1"
commons-io = "commons-io:commons-io:2.21.0"
guava = "com.google.guava:guava:33.5.0-jre"
gson = "com.google.code.gson:gson:2.13.2"
fastutil = "it.unimi.dsi:fastutil:8.5.18"
caffeine = "com.github.ben-manes.caffeine:caffeine:3.2.3"
jetbrains-annotations = "org.jetbrains:annotations:26.1.0"
reflect = "net.lenni0451:Reflect:1.6.2"
lambdaevents = "net.lenni0451:LambdaEvents:2.4.2"
minecraftauth = "net.raphimc:MinecraftAuth:5.0.1-SNAPSHOT"
grpc-proto = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-services = { module = "io.grpc:grpc-services", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc" }
protobuf-bom = { module = "com.google.protobuf:protobuf-bom", version.ref = "protobuf" }
protobuf-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
netty-bom = "io.netty:netty-bom:4.2.10.Final"
armeria-bom = { module = "com.linecorp.armeria:armeria-bom", version.ref = "armeria" }
armeria = { module = "com.linecorp.armeria:armeria" }
armeria-grpc = { module = "com.linecorp.armeria:armeria-grpc" }
armeria-grpc-protocol = { module = "com.linecorp.armeria:armeria-grpc-protocol" }
armeria-prometheus1 = { module = "com.linecorp.armeria:armeria-prometheus1" }
armeria-tomcat10 = { module = "com.linecorp.armeria:armeria-tomcat10" }
reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "reactor-core" }
reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactor-core" }
reactor-netty-core = { module = "io.projectreactor.netty:reactor-netty-core", version.ref = "reactor-netty" }
reactor-netty-http = { module = "io.projectreactor.netty:reactor-netty-http", version.ref = "reactor-netty" }
spark = "me.lucko:spark-common:1.10.142-SNAPSHOT"
openai = "com.openai:openai-java:4.21.0"
immutables-value = "org.immutables:value:2.12.1"
immutables-gson = "org.immutables:gson:2.12.1"
jooq-lib = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-codegen = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }
jooq-meta-extensions = { module = "org.jooq:jooq-meta-extensions", version.ref = "jooq" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }
hikaricp = "com.zaxxer:HikariCP:7.0.2"
mariadb = "org.mariadb.jdbc:mariadb-java-client:3.5.7"
sqlite = "org.xerial:sqlite-jdbc:3.51.2.0"
acme4j = "org.shredzone.acme4j:acme4j-client:4.0.0"
kotlin-bom = "org.jetbrains.kotlin:kotlin-bom:2.3.10"
classtransform-mixinstranslator = { module = "net.lenni0451.classtransform:mixinstranslator", version.ref = "classtransform" }
classtransform-additionalclassprovider = { module = "net.lenni0451.classtransform:additionalclassprovider", version.ref = "classtransform" }
kyori-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "kyori" }
kyori-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "kyori" }
kyori-ansi = { module = "net.kyori:adventure-text-serializer-ansi", version.ref = "kyori" }
angus = "org.eclipse.angus:angus-mail:2.0.5"
javax-annotations = "javax.annotation:javax.annotation-api:1.3.2"
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit = "org.junit.jupiter:junit-jupiter:6.0.3"
evalex = "com.ezylang:EvalEx:3.6.0"

[bundles]
bom = ["netty-bom", "armeria-bom", "protobuf-bom", "kotlin-bom"]
log4j = ["log4j-api", "log4j-core", "log4j-slf4j2-impl", "log4j-iostreams", "log4j-jul"]
grpc = ["grpc-proto", "grpc-services", "grpc-stub", "grpc-netty", "protobuf-util"]
ansi4j = ["ansi4j-core-api", "ansi4j-core-impl"]
armeria = ["armeria", "armeria-grpc", "armeria-grpc-protocol", "armeria-prometheus1", "armeria-tomcat10"]
reactor-netty = ["reactor-netty-core", "reactor-netty-http"]
jooq = ["jooq-lib"]
classtransform = ["classtransform-mixinstranslator", "classtransform-additionalclassprovider"]
kyori = ["kyori-plain", "kyori-gson", "kyori-ansi"]
